### ISSUE TITLE
轻服务能否支持本地调试

### ISSUE THREAD

**Issue by ZhangBohan** [bytedance/byteinspire-js-sdk#3]
轻服务是否可以支持本地通过Koa或者Express转发请求支持本地调试，目前纯远程调试非常不友好

**Comment by adcentury** [comment]
@ZhangBohan 你好，感谢反馈，云函数目前只能通过在线进行调试。不过近期我们会上线一个名为「云工程」的方案，允许你在本地起一个 Express 或 Koa 项目，使用本地调试，同时还能享有轻服务开箱即用的资源。

**Comment by ZhangBohan** [comment]
@adcentury 这个有Roadmap吗，大概什么时间可以用上
