### ISSUE TITLE
用你们文档的上传文件示例测试，文件上传报500，这什么鬼

### ISSUE THREAD

**Issue by qidaneix** [bytedance/byteinspire-js-sdk#37]
没有单测吗

**Comment by Margaux7** [comment]
你好，文件服务的后端昨天有改动，现在已经修复了，你可以再试试

**Comment by Margaux7** [comment]
> 没有单测吗
你好，文件服务的后端昨天有改动，现在已经修复了，你可以再试试

**Comment by qidaneix** [comment]
> > 没有单测吗
> > 你好，文件服务的后端昨天有改动，现在已经修复了，你可以再试试

可以了
